In [28]:
import torch

# Declare Dropout layer with 0.5 Probability

In [29]:
p = 0.5
module = torch.nn.Dropout(p)

# It will have Training Mode as Default

In [30]:
module.training

True

# It shutdowns 50% randomly and it'll multipy 1/1-p with other elements to make up for this removal

In [31]:
inp = torch.ones(1, 10)
module(inp)

tensor([[2., 0., 0., 0., 2., 0., 2., 2., 0., 0.]])

In [32]:
module(inp)

tensor([[2., 0., 0., 0., 2., 2., 0., 0., 2., 2.]])

In [33]:
1/(1-p)

2.0

# Let's set it into Eval Mode

In [34]:
module.eval()

Dropout(p=0.5, inplace=False)

In [35]:
module.training

False

In [36]:
module(inp)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [37]:
module(inp)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])