In [88]:
import torch
from torch import nn
import math

# Input Tensor

In [89]:
inp = torch.tensor([[0, 4], [-1, 7], [3, 5]], dtype=torch.float)
n_samples, n_features = inp.shape

print("n_samples :", n_samples)
print("n_features:", n_features)

n_samples : 3
n_features: 2


# Get Normalized Values with Layer Norm

In [90]:
module = nn.LayerNorm(n_features, elementwise_affine=False)

In [91]:
module(inp)

tensor([[-1.0000,  1.0000],
        [-1.0000,  1.0000],
        [-1.0000,  1.0000]])

In [92]:
module(inp).mean(-1), module(inp).std(-1, correction=0)

(tensor([0., 0., 0.]), tensor([1.0000, 1.0000, 1.0000]))

# Calculate Manually

In [93]:
inp.mean(-1), inp.std(-1, correction=0)

(tensor([2., 3., 4.]), tensor([2., 4., 1.]))

In [94]:
print((0. - 2.) / math.sqrt((2. ** 2) + 1e-20), (4. - 2.) / math.sqrt((2. ** 2) + 1e-20))
print((-1. - 3.) / math.sqrt((4. ** 2) + 1e-20), (7. - 3.) / math.sqrt((4. ** 2) + 1e-20))
print((3. - 4.) / math.sqrt((1. ** 2) + 1e-20), (5. - 4.) / math.sqrt((1. ** 2) + 1e-20))

-1.0 1.0
-1.0 1.0
-1.0 1.0
